language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

services: postgresql

env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q psycopg2
  - python setup.py -q install

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python --version
  - django-admin.py --version
  - python ./example/manage.py test example --settings=example.test_settings

sudo: false

