language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

services: postgresql

env:
  - DJANGO_VERSION=1.8.12
  - DJANGO_VERSION=1.9.5

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.9.5

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q psycopg2
  - python setup.py -q install

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - django-admin.py --version
  - python ./example/manage.py test example --settings=example.test_settings
